# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirestoreLoginView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirestoreLoginView
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'RxFirebase/Auth'
  pod 'Firebase/Core'

  target 'FirestoreLoginViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirestoreLoginViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
